apiVersion: apps/v1
kind: Deployment
metadata:
  name: agnhost-deployment
  labels:
    app: agnhost
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agnhost
  template:
    metadata:
      labels:
        app: agnhost
    spec:
      containers:
      - name: agnhost
        image: registry.k8s.io/e2e-test-images/agnhost:2.39
        args: ["netexec", "--http-port=8080"]
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: agnhost-service
spec:
  selector:
    app: agnhost
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer