name: Node.js CI/CD

on:
  push:
    branches: [ master, container ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Generate version
      id: version
      run: |
        echo "version=$(date +'%Y%m%d_%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Build and push Docker image 
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
        IMAGE_TAG: ${{ steps.version.outputs.version }}
      run: |
        # buildx 설정
        docker buildx create --name mybuilder --use
        docker buildx inspect --bootstrap
        
        # 멀티 플랫폼 빌드 및 푸시
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG \
          -t $ECR_REGISTRY/$ECR_REPOSITORY:latest \
          --push .

  deploy:
    needs: build-and-push
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
    
    - name: Create SSH directory
      run: mkdir -p ~/.ssh
    
    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
    - name: Add EC2 host to known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
          env:
            ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
            ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}  # 이 부분이 하드코딩되어 있던 것을 수정
            IMAGE_TAG: ${{ needs.build-and-push.outputs.version }}  # version을 이전 job에서 가져오도록 수정
            EC2_HOST: ${{ secrets.EC2_HOST }}
            EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
          run: |
            # EC2에 환경 변수를 전달하는 방식 수정
            ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST "docker pull ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG} && \
              docker stop sample-server || true && \
              docker rm sample-server || true && \
              docker run -d --name sample-server \
                -p 3000:3000 \
                ${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}"