name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run build
      
    - name: Generate version
      id: version
      run: |
        echo "timestamp=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT
        echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.node-version }}-${{ steps.version.outputs.timestamp }}-${{ steps.version.outputs.sha_short }}
        path: |
          dist
          package.json
          package-lock.json
          tsconfig.json
          tsconfig.build.json

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' # master 브랜치에 푸시된 경우에만 실행
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files-20.x-${{ needs.build.outputs.timestamp }}-${{ needs.build.outputs.sha_short }}
    
    - name: Create SSH directory
      run: mkdir -p ~/.ssh
    
    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
    - name: Add EC2 host to known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        VERSION: ${{ needs.build.outputs.timestamp }}-${{ needs.build.outputs.sha_short }}
      run: |
        # 버전별 디렉토리 생성
        ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST "mkdir -p ~/deployments/$VERSION"
        
        # 파일 복사
        scp -i ~/.ssh/id_rsa -r \
          dist \
          package.json \
          package-lock.json \
          tsconfig.json \
          tsconfig.build.json \
          $EC2_USERNAME@$EC2_HOST:~/deployments/$VERSION/
        
        # 심볼릭 링크 업데이트
        ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST '
          cd ~/deployments
          rm -f current
          ln -s $VERSION current
          cd $VERSION
          npm ci
          pm2 stop sample-server || true
          pm2 start dist/main.js --name sample-server
          
          # 최근 5개 버전만 유지
          cd ~/deployments
          ls -t | grep -v current | tail -n +6 | xargs rm -rf
        '