name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Build
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ matrix.node-version }}
        path: |
          dist
          package.json
          package-lock.json
          tsconfig.json
          tsconfig.build.json

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master' # master 브랜치에 푸시된 경우에만 실행
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files-20.x
    
    - name: Create SSH directory
      run: mkdir -p ~/.ssh
    
    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
    - name: Add EC2 host to known_hosts
      run: |
        echo "${{ secrets.EC2_HOST_KEY }}" >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
      run: |
        scp -i ~/.ssh/id_rsa -r \
          dist \
          package.json \
          package-lock.json \
          tsconfig.json \
          tsconfig.build.json \
          $EC2_USERNAME@$EC2_HOST:~/sample-server

        ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST '
          cd ~/sample-server
          npm ci
          pm2 stop sample-server || true
          pm2 start dist/main.js --name sample-server
        '