name: Node.js CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v4
    
    - name: Generate version
      id: version
      run: |
        echo "version=$(date +'%Y%m%d_%H%M%S')-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
      
    - name: Build
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-files-${{ steps.version.outputs.version }}
        path: |
          dist
          package.json
          package-lock.json
          tsconfig.json
          tsconfig.build.json

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-files-${{ needs.build.outputs.version }}
    
    - name: Create SSH directory
      run: mkdir -p ~/.ssh
    
    - name: Add SSH key
      run: |
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
    
    - name: Add EC2 host to known_hosts
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        ssh-keyscan -H $EC2_HOST >> ~/.ssh/known_hosts
    
    - name: Deploy to EC2
      env:
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
        VERSION: ${{ needs.build.outputs.version }}
      run: |
        # 버전별 디렉토리 생성
        ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST "
          mkdir -p ~/deployments/$VERSION
        "
        
        # 버전 디렉토리에 파일 복사
        scp -i ~/.ssh/id_rsa -r \
          dist \
          package.json \
          package-lock.json \
          tsconfig.json \
          tsconfig.build.json \
          $EC2_USERNAME@$EC2_HOST:~/deployments/$VERSION/
        
        # 버전 디렉토리에서 애플리케이션 실행
        ssh -i ~/.ssh/id_rsa $EC2_USERNAME@$EC2_HOST '
          cd ~/deployments/$VERSION
          npm ci
          pm2 stop sample-server || true
          pm2 start dist/main.js --name sample-server
          
          # 최근 5개 버전만 유지
          cd ~/deployments
          ls -t | grep -v current | tail -n +6 | xargs rm -rf
        '